// ─── Content data (ES + EN) ───
// Edit this file to update content without touching JSX.

const i18n = {
  es: {
    nav: {
      home: "Inicio",
      about: "Sobre mí",
      experience: "Experiencia",
      education: "Educación",
      projects: "Proyectos",
      skills: "Skills",
      certs: "Certificaciones",
      languages: "Idiomas",
      contact: "Contacto",
    },
    hero: {
      pill: "Portfolio · Valencia, ES",
      name: "Zakaria",
      surname: "Abouhammadi",
      role: "Machine Learning Engineer",
      bio: "Estudiante de último curso del Grado en Ingeniería Informática en la ETSE de la Universitat de València. Actualmente Machine Learning Engineer en prácticas en Solver Intelligent Analytics, construyendo sistemas reales de IA con LLMs, RAG y agentes para la administración pública.",
      ctaPrimary: "Ver proyectos",
      ctaSecondary: "Descargar CV",
    },
    s_about: {
      h2: "Construyendo sistemas de IA con propósito real.",
      desc: "Estudiante de último curso, todavía aprendiendo, pero con la cabeza puesta en montar cosas que de verdad funcionen y acaben en producción: LLMs, RAG, agentes. Me preocupa que el pipeline esté bien pensado, que lo que sale se pueda evaluar y que las decisiones queden documentadas para el siguiente que toque el código.",
      cardBio: "Compagino el último curso del grado con las prácticas en Solver y mucho trabajo autodidacta. La mayoría de lo que sé de LLMs y RAG viene de construir proyectos, romperlos y entender por qué fallan.",
      stats: [
        { n: "30", l: "Proyectos" },
        { n: "39", l: "Certificaciones" },
        { n: "400h", l: "Prácticas en Solver" },
        { n: "5", l: "Idiomas" },
      ],
    },
    s_exp: {
      h2: "Construyendo sistemas reales de IA en Solver Intelligent Analytics.",
      desc: "Asistente conversacional con RAG para el Comú d'Encamp (Andorra): chatbot multilingüe en producción para la administración municipal, con generación automática de pliegos de contratación pública.",
      role: "Machine Learning Engineer · Prácticas",
      org: "Solver Intelligent Analytics",
      where: "Valencia · Híbrido",
      when: "ene 2026 — actualidad · 5 meses · 400 h",
      desc_long: "Desarrollo de un asistente conversacional con RAG para el Comú d'Encamp (Andorra): un chatbot multilingüe en producción que integra distintas funcionalidades para la administración municipal. Una de las funcionalidades principales es la generación automática de pliegos de contratación pública: mediante un flujo conversacional orquestado con LangGraph, el sistema recoge los datos necesarios del usuario y produce el documento final en formato Word, cubriendo doce variantes según el tipo de procedimiento. El módulo cubre el flujo end-to-end: extracción y validación de datos, plantillado DOCX a nivel XML e integración con SharePoint vía Microsoft Graph para mantener sincronizadas las plantillas y ejemplos del cliente.",
      pipelineLabel: "PIPELINE",
      pipeline: ["Conversación guiada", "Validación de datos", "Plantillado DOCX (XML)", "SharePoint · Graph"],
      stackLabel: "Stack",
      active: "En activo",
    },
    s_edu: {
      h2: "Universitat de València · Ingeniería Informática.",
      desc: "Último curso del grado, compaginado con prácticas curriculares y extracurriculares en Solver y formación autodidacta continua en LLMs, RAG, agentes, PyTorch y stacks modernos de backend.",
      degree: "Grado en Ingeniería Informática",
      org: "Universitat de València · Escola Tècnica Superior d'Enginyeria (ETSE)",
      when: "sep 2022 — sep 2026 · 4 años",
      subjects: [
        "Estructura de datos y algoritmos",
        "Sistemas inteligentes",
        "Ingeniería del software",
        "Bases de datos",
        "Redes",
        "Desarrollo de aplicaciones web",
      ],
      highlights: "Asignaturas destacadas",
    },
    s_proj: {
      h2: "Una selección de proyectos.",
      desc: "LLMs, RAG, agentes, deep learning y un puñado de sistemas. Filtra por categoría o despliega el archivo completo.",
      filterAll: "Todos",
      filterLabels: { llm: "LLMs · Agents · RAG", dl: "Deep Learning", ml: "Machine Learning", sys: "Sistemas · Otros" },
      seeMore: "Ver el archivo completo",
      seeLess: "Ver menos",
      privateRepo: "Repositorio privado",
      viewRepo: "Ver repositorio",
    },
    s_skills: {
      h2: "Stack y herramientas.",
      desc: "Lo que uso a diario y lo que aparece en mis proyectos. Más detalle en cada repositorio.",
    },
    s_certs: {
      h2: "39 certificaciones, todas verificables.",
      desc: "DeepLearning.AI, IBM, Google Cloud, Packt, NVIDIA y University of Michigan. Cada tarjeta enlaza al certificado en Coursera.",
      verify: "Ver certificado",
    },
    s_langs: {
      h2: "Cinco idiomas, dos nativos.",
      desc: "Trabajo en español e inglés. Hablo bereber y árabe de forma nativa, francés a nivel profesional.",
    },
    s_contact: {
      h2: "Hablamos.",
      desc: "Estoy abierto a oportunidades en IA/ML, sobre todo LLMs, RAG y sistemas agénticos. Si buscas alguien que combine investigación aplicada con producción real, escríbeme.",
      copy: "Copiar email",
      copied: "Copiado",
      cvEs: "CV (Español)",
      cvEn: "CV (English)",
    },
    footer: {
      copy: "Zakaria Abouhammadi · Valencia, España · 2026",
    },
  },

  en: {
    nav: {
      home: "Home",
      about: "About",
      experience: "Experience",
      education: "Education",
      projects: "Projects",
      skills: "Skills",
      certs: "Certifications",
      languages: "Languages",
      contact: "Contact",
    },
    hero: {
      pill: "Portfolio · Valencia, ES",
      name: "Zakaria",
      surname: "Abouhammadi",
      role: "Machine Learning Engineer",
      bio: "Final-year Computer Science Engineering student at the School of Engineering (ETSE) of the University of Valencia. Currently Machine Learning Engineer intern at Solver Intelligent Analytics, building real AI systems with LLMs, RAG and agents for public administration.",
      ctaPrimary: "View projects",
      ctaSecondary: "Download CV",
    },
    s_about: {
      h2: "Building AI systems with real-world purpose.",
      desc: "Final-year CS student, still learning, but focused on building things that actually run in production: LLMs, RAG, agents. I care about pipelines being well thought out, outputs being measurable, and decisions being documented for whoever picks up the code next.",
      cardBio: "I combine the final year of my degree with the internship at Solver and a lot of self-driven work. Most of what I know about LLMs and RAG comes from building projects, breaking them and figuring out why they fail.",
      stats: [
        { n: "30", l: "Projects" },
        { n: "39", l: "Certifications" },
        { n: "400h", l: "Internship at Solver" },
        { n: "5", l: "Languages" },
      ],
    },
    s_exp: {
      h2: "Building real AI systems at Solver Intelligent Analytics.",
      desc: "Conversational RAG assistant for the Comú d'Encamp (Andorra): a multilingual production chatbot for the municipal administration, with automatic generation of public procurement documents.",
      role: "Machine Learning Engineer · Internship",
      org: "Solver Intelligent Analytics",
      where: "Valencia · Hybrid",
      when: "Jan 2026 — Present · 5 months · 400 h",
      desc_long: "Built a conversational RAG assistant for the Comú d'Encamp (Andorra): a multilingual production chatbot integrating multiple functionalities for the municipal administration. One of the main features is the automatic generation of public procurement documents: through a guided conversational flow orchestrated with LangGraph, the system collects the required information from the user and produces the final Word document, covering twelve variants depending on the procedure type. The module covers the end-to-end flow: data extraction and validation, XML-level DOCX templating, and SharePoint integration via Microsoft Graph to keep the client's templates and examples synchronized.",
      pipelineLabel: "PIPELINE",
      pipeline: ["Guided conversation", "Data validation", "DOCX templating (XML)", "SharePoint · Graph"],
      stackLabel: "Stack",
      active: "Currently working",
    },
    s_edu: {
      h2: "University of Valencia · Computer Science Engineering.",
      desc: "Final year of the degree, combined with curricular and extracurricular internships at Solver and continuous self-taught training on LLMs, RAG, agents, PyTorch and modern backend stacks.",
      degree: "BSc in Computer Science Engineering",
      org: "Universitat de València · School of Engineering (ETSE)",
      when: "Sep 2022 — Sep 2026 · 4 years",
      subjects: [
        "Data Structures & Algorithms",
        "Intelligent Systems",
        "Software Engineering",
        "Databases",
        "Computer Networks",
        "Web Development",
      ],
      highlights: "Highlighted subjects",
    },
    s_proj: {
      h2: "Selected work.",
      desc: "LLMs, RAG, agents, deep learning and a handful of systems projects. Filter by category or expand the full archive.",
      filterAll: "All",
      filterLabels: { llm: "LLMs · Agents · RAG", dl: "Deep Learning", ml: "Machine Learning", sys: "Systems · Other" },
      seeMore: "View full archive",
      seeLess: "Show less",
      privateRepo: "Private repository",
      viewRepo: "View repo",
    },
    s_skills: {
      h2: "Stack & tools.",
      desc: "What I use daily and what shows up in my projects. More detail in each repository.",
    },
    s_certs: {
      h2: "39 certifications, all verifiable.",
      desc: "DeepLearning.AI, IBM, Google Cloud, Packt, NVIDIA and University of Michigan. Each card links to the Coursera certificate.",
      verify: "View certificate",
    },
    s_langs: {
      h2: "Five languages, two native.",
      desc: "I work in Spanish and English. I speak Berber and Arabic natively, French at a professional level.",
    },
    s_contact: {
      h2: "Let's talk.",
      desc: "I'm open to opportunities in AI/ML, especially LLMs, RAG and agentic systems. If you're looking for someone who pairs applied research with real production, reach out.",
      copy: "Copy email",
      copied: "Copied",
      cvEs: "CV (Spanish)",
      cvEn: "CV (English)",
    },
    footer: {
      copy: "Zakaria Abouhammadi · Valencia, Spain · 2026",
    },
  },
};

// ─── Projects ─────────────────────────────────────────────────────────────
// 28 public + 1 private (asistente-uv, TFG) = 29 total
// `featured: true` shows in the top grid; the rest go to the full archive.
// `accent` only drives the card art palette.

const PROJECTS = [
  {
    id: "yolo-v1",
    name: "yolo_v1",
    subtitle: "Object Detection · From Scratch",
    cat: "dl",
    desc_es: "Implementación desde cero de YOLOv1 (Redmon et al., 2016) en PyTorch, adaptada para entrenar sobre COCO 2017 con 80 clases en lugar de las 20 de PASCAL VOC. Dos backbones: Darknet entrenado desde cero (24 conv + 2 FC) y una variante con ResNet18 preentrenado. Rejilla de detección 7×7, 2 cajas por celda, loss original de cinco términos, entrenamiento distribuido (DDP) con precisión mixta (AMP), warmup lineal y cosine annealing. Incluye 38 tests con pytest y una documentación detallada de dos bugs silenciosos encontrados durante el desarrollo.",
    desc_en: "From-scratch implementation of YOLOv1 (Redmon et al., 2016) in PyTorch, adapted to train on COCO 2017 with 80 classes instead of PASCAL VOC's 20. Two backbones: a Darknet trained from scratch (24 conv + 2 FC) and a variant with a pretrained ResNet18. 7×7 detection grid, 2 boxes per cell, the original five-term loss, distributed training (DDP) with mixed precision (AMP), linear warmup and cosine annealing. Ships 38 pytest tests and a detailed write-up of two silent bugs found during development.",
    stack: ["PyTorch", "DDP", "AMP", "COCO 2017", "ResNet18", "pytest"],
    href: "https://github.com/Zakariajava/yolo_v1",
    accent: "lilac",
    featured: true,
  },
  {
    id: "asistente-uv",
    name: "asistente-uv",
    subtitle: "TFG · RAG Agent",
    cat: "llm",
    desc_es: "Mi Trabajo de Fin de Grado: un asistente RAG que responde preguntas sobre la Universitat de València usando información oficial extraída de uv.es. Combina una base local de documentos indexados con búsqueda web en tiempo real cuando la información no está disponible, y se enriquece automáticamente con cada consulta. Agente ReAct sobre LangGraph con retrieval híbrido (BM25 + dense + RRF) y scraping con Playwright.",
    desc_en: "My Bachelor's final project: a RAG assistant that answers questions about the University of Valencia using official information extracted from uv.es. It combines a local document store with real-time web search when information is missing, and grows automatically with every new query. ReAct-style agent on LangGraph with hybrid retrieval (BM25 + dense + RRF) and Playwright-based scraping.",
    stack: ["LangGraph", "Ollama", "ChromaDB", "BM25", "Playwright", "FastAPI", "React", "Docker"],
    href: null,
    privateRepo: true,
    accent: "violet",
    featured: true,
  },
  {
    id: "codescribe",
    name: "CodeScribe",
    subtitle: "LLM · CLI Tool",
    cat: "llm",
    desc_es: "Herramienta de línea de comandos que escanea un proyecto entero y añade documentación y comentarios a cada fichero fuente usando un LLM local vía Ollama. Pipeline determinista construido con LangGraph: escaneo → clasificación → chunking → LLM → post-procesado → escritura. Soporta dry-run con diff, backups, menú interactivo y generación automática de README.",
    desc_en: "A CLI tool that scans an entire project and adds documentation and comments to every source file using a local LLM via Ollama. The pipeline is built with LangGraph for a deterministic, debuggable flow: scan → classify → chunk → LLM → post-process → write back. Supports dry-run with diff, backups, an interactive settings menu and automatic README generation.",
    stack: ["Python", "LangGraph", "Ollama", "Click", "Rich", "uv"],
    href: "https://github.com/Zakariajava/CodeScribe",
    accent: "slate",
    featured: true,
  },
  {
    id: "chatbot",
    name: "chatbot",
    subtitle: "LLM · Multilingual RAG",
    cat: "llm",
    desc_es: "Sistema de QA conversacional con retrieval híbrido (BM25 + dense) fusionado con Reciprocal Rank Fusion, citas estrictas por chunk, enriquecimiento web adaptativo con Selenium y memoria a corto/largo plazo en SQLite. Todo orquestado en un único grafo de LangGraph con nodos contractualizados. Multilingüe de principio a fin.",
    desc_en: "Conversational QA system with hybrid retrieval (BM25 + dense embeddings) fused via Reciprocal Rank Fusion, strict chunk-level citations, adaptive Selenium-based web enrichment and short/long-term memory backed by SQLite. Everything orchestrated in a single LangGraph instance with clearly contracted nodes. End-to-end multilingual.",
    stack: ["LangGraph", "BM25", "Dense Embeddings", "RRF", "SQLite", "Selenium"],
    href: "https://github.com/Zakariajava/chatbot",
    accent: "blue",
    featured: true,
  },
  {
    id: "llama-4-scratch",
    name: "llama_4_scratch",
    subtitle: "Transformers · From Scratch",
    cat: "llm",
    desc_es: "Implementación y explicación paso a paso de los componentes clave de un transformer tipo LLaMA: tokenizador, scaled dot-product attention y Multi-Head Latent Attention. Cada operación comentada con ejemplos numéricos y visualizaciones para entender qué ocurre por dentro en vez de limitarme a usar una librería.",
    desc_en: "From-scratch implementation and step-by-step explanation of the key components of a LLaMA-style transformer: tokenizer, scaled dot-product attention and Multi-Head Latent Attention. Every operation is commented with numerical examples and visualizations to understand what's happening under the hood rather than just using a library.",
    stack: ["PyTorch", "NumPy", "Jupyter"],
    href: "https://github.com/Zakariajava/llama_4_scratch",
    accent: "lilac",
    featured: true,
  },
  {
    id: "givemecredit",
    name: "GiveMeSomeCredit",
    subtitle: "Credit Risk · PyTorch",
    cat: "ml",
    desc_es: "Baseline limpio y reproducible para predecir la probabilidad de impago grave a dos años con PyTorch. Cubre auditoría de datos, imputación por mediana, recortes por cuantiles, transformaciones log1p, RobustScaler, una MLP con BatchNorm y GELU, entrenamiento con precisión mixta y early stopping sobre ROC-AUC, más evaluación completa con curvas ROC y Precision–Recall.",
    desc_en: "Clean, reproducible baseline to predict the probability of serious delinquency within two years using PyTorch. Covers data audit, median imputation, quantile clipping, log1p transforms, RobustScaler, an MLP with BatchNorm and GELU, mixed-precision training and early stopping on ROC-AUC, plus full evaluation with ROC and Precision–Recall curves.",
    stack: ["PyTorch", "scikit-learn", "pandas", "MLP", "AMP"],
    href: "https://github.com/Zakariajava/GiveMeSomeCredit",
    accent: "green",
    featured: true,
  },
  {
    id: "multiquery-hyde-rag",
    name: "multiquery-hyde-rag",
    subtitle: "RAG · Advanced",
    cat: "llm",
    desc_es: "Pipeline de RAG que combina multi-query retrieval (reformulación automática de la pregunta en varias variantes) con HyDE (Hypothetical Document Embeddings) sobre ChromaDB Cloud. Busca mejorar el recall en preguntas ambiguas o mal formuladas.",
    desc_en: "A RAG pipeline combining multi-query retrieval (automatic rewriting of the question into several variants) with HyDE (Hypothetical Document Embeddings) on ChromaDB Cloud. Aims to improve recall on ambiguous or poorly phrased queries.",
    stack: ["ChromaDB", "HyDE", "LangChain"],
    href: "https://github.com/Zakariajava/multiquery-hyde-rag-chroma-cloud",
    accent: "cyan",
    featured: true,
  },
  {
    id: "multiagent-debate",
    name: "MultiagentDebate",
    subtitle: "Multi-Agent",
    cat: "llm",
    desc_es: "Sistema multiagente en el que varios LLMs actúan como participantes en un debate estructurado, con un juez que evalúa los argumentos. Explora cómo la confrontación de ideas entre modelos puede mejorar la calidad del razonamiento final.",
    desc_en: "A multi-agent system where several LLMs act as participants in a structured debate, with a judge that evaluates the arguments. Useful to explore how confronting ideas between models can improve the final reasoning quality.",
    stack: ["Python", "LLMs", "Multi-Agent"],
    href: "https://github.com/Zakariajava/MultiagentDebate",
    accent: "pink",
    featured: true,
  },
  {
    id: "vision-transformer",
    name: "VisionTransformer",
    subtitle: "Computer Vision",
    cat: "dl",
    desc_es: "Implementación de un Vision Transformer para clasificación de imágenes siguiendo el paper original: patch embedding, positional encoding, encoder transformer y cabeza de clasificación. Análisis comparativo con arquitecturas CNN tradicionales.",
    desc_en: "Implementation of a Vision Transformer for image classification following the original paper: patch embedding, positional encoding, transformer encoder and classification head. Comparative analysis against traditional CNN architectures.",
    stack: ["PyTorch", "Transformers", "CV"],
    href: "https://github.com/Zakariajava/VisionTransformer",
    accent: "slate",
    featured: true,
  },

  // ── Compact / archive (real repos)
  {
    id: "data-chat",
    name: "data-chat",
    subtitle: "Agents · Text-to-SQL",
    cat: "llm",
    desc_es: "Exploración de patrones de text-to-SQL y data chat con agentes: convertir preguntas en lenguaje natural en consultas estructuradas sobre conjuntos de datos, ejecutarlas y devolver la respuesta ya resumida. Base para futuros asistentes analíticos.",
    desc_en: "Exploration of text-to-SQL and data chat patterns with agents: turn natural language questions into structured queries over datasets, execute them and return summarized answers. A base for future analytical assistants.",
    stack: ["LangChain", "LLMs", "SQL"],
    href: "https://github.com/Zakariajava/data-chat",
    accent: "blue",
  },
  {
    id: "bm25-dense-retrieval",
    name: "bm25-dense-retrieval",
    subtitle: "Information Retrieval",
    cat: "llm",
    desc_es: "Estudio práctico del retrieval híbrido: combinar BM25 (léxico) con dense embeddings (semántico) para superar las limitaciones de cada uno por separado. Experimentos con Reciprocal Rank Fusion y comparativa de rendimiento según el tipo de pregunta.",
    desc_en: "Practical study of hybrid retrieval: combining BM25 (lexical) with dense embeddings (semantic) to go beyond the limits of either approach on its own. Experiments with Reciprocal Rank Fusion and performance comparison across query types.",
    stack: ["BM25", "Embeddings", "RRF"],
    href: "https://github.com/Zakariajava/bm25-dense-etrieval",
    accent: "cyan",
  },
  {
    id: "advanced-hyde-rag",
    name: "advanced-hyde-rag",
    subtitle: "RAG · HyDE",
    cat: "llm",
    desc_es: "Versión más elaborada del pipeline HyDE con reescritura de consulta, generación de documentos hipotéticos y reranking semántico posterior al retrieval inicial. Sirve para entender dónde están los cuellos de botella de calidad en un sistema RAG real.",
    desc_en: "A more elaborate version of the HyDE pipeline with query rewriting, hypothetical document generation and semantic reranking after the initial retrieval step. Useful to understand where the quality bottlenecks sit in a real RAG system.",
    stack: ["HyDE", "Reranking", "Embeddings"],
    href: "https://github.com/Zakariajava/advanced-hyde-rag",
    accent: "violet",
  },
  {
    id: "ranked-rag-pipeline",
    name: "ranked-rag-pipeline",
    subtitle: "RAG · Reranking",
    cat: "llm",
    desc_es: "Pipeline de RAG con cross-encoder reranker para elevar la precisión del contexto antes de pasárselo al LLM. Experimentación con distintos modelos de reranking y análisis del impacto en la calidad de las respuestas.",
    desc_en: "A RAG pipeline with a cross-encoder reranker to boost context precision before passing it to the LLM. Experimentation with different reranking models and analysis of their impact on final answer quality.",
    stack: ["Cross-Encoder", "Sentence Transformers"],
    href: "https://github.com/Zakariajava/ranked-rag-pipeline",
    accent: "lilac",
  },
  {
    id: "poetry-transformer",
    name: "PoetryTransformerPredict",
    subtitle: "NLP · Generation",
    cat: "dl",
    desc_es: "Modelo transformer autoregresivo entrenado para generar poesía carácter a carácter. Experimento para entender en profundidad el proceso de entrenamiento, el sampling con temperatura y el comportamiento del modelo en dominios creativos.",
    desc_en: "An autoregressive transformer model trained to generate poetry character by character. An experiment to deeply understand the training process, temperature-based sampling and model behavior in creative domains.",
    stack: ["PyTorch", "Transformers", "NLP"],
    href: "https://github.com/Zakariajava/PoetryTransformerPredict",
    accent: "pink",
  },
  {
    id: "brain-tumor",
    name: "Brain-Tumor-Classification",
    subtitle: "Medical Imaging · CNN",
    cat: "dl",
    desc_es: "Clasificación automática de imágenes de resonancia magnética cerebral entre cuatro clases (glioma, meningioma, pituitario y sano) con redes convolucionales. Aumento de datos, transfer learning desde modelos preentrenados y análisis de matriz de confusión.",
    desc_en: "Automatic classification of brain MRI images across four classes (glioma, meningioma, pituitary and healthy) with convolutional networks. Data augmentation, transfer learning from pretrained models and confusion-matrix analysis.",
    stack: ["TensorFlow", "CNN", "Transfer Learning"],
    href: "https://github.com/Zakariajava/Brain-Tumor-Classification",
    accent: "violet",
  },
  {
    id: "amazigh-ocr",
    name: "Amazigh-Alphabets-Recognition",
    subtitle: "OCR · Tifinagh",
    cat: "dl",
    desc_es: "Reconocimiento de caracteres manuscritos del alfabeto tifinagh (lengua amazigh) con redes convolucionales. Un proyecto con componente personal y cultural además de técnico: la escasez de datasets disponibles obliga a un trabajo cuidadoso de preparación y aumentación.",
    desc_en: "Recognition of handwritten characters of the tifinagh alphabet (Amazigh language) using convolutional networks. A project with a personal and cultural angle beyond the technical one: the scarcity of available datasets calls for careful data preparation and augmentation.",
    stack: ["CNN", "OCR", "Data Augmentation"],
    href: "https://github.com/Zakariajava/Amazigh-Alphabets-Recognition",
    accent: "cyan",
  },
  {
    id: "handwritten-alpha",
    name: "Handwritten-Alphabets-Recognition",
    subtitle: "OCR",
    cat: "dl",
    desc_es: "Red neuronal convolucional para clasificar letras manuscritas del alfabeto latino. Proyecto inicial de visión por computador para afianzar el flujo completo: preparación de datos, diseño del modelo, entrenamiento con validación y evaluación final.",
    desc_en: "A convolutional network to classify handwritten letters of the Latin alphabet. An early computer vision project to nail down the full workflow: data preparation, model design, training with validation and final evaluation.",
    stack: ["CNN", "Keras"],
    href: "https://github.com/Zakariajava/Handwritten-Alphabets-Recognition",
    accent: "slate",
  },
  {
    id: "handwritten-digit",
    name: "Handwritten-Digit-Recognition",
    subtitle: "OCR · MNIST",
    cat: "dl",
    desc_es: "El clásico de todo el que empieza con deep learning: una red convolucional entrenada sobre MNIST. Lo mantengo en el portfolio porque fue el primer contacto práctico con el campo y me permitió entender las piezas básicas que se repiten en arquitecturas más complejas.",
    desc_en: "The classic starting point for everyone getting into deep learning: a convolutional network trained on MNIST. I keep it in the portfolio because it was my first hands-on contact with the field and helped me understand the building blocks that show up in every more complex architecture.",
    stack: ["TensorFlow", "CNN", "MNIST"],
    href: "https://github.com/Zakariajava/Handwritten-Digit-Recognition",
    accent: "blue",
  },
  {
    id: "ecommerce-fraud",
    name: "E-Commerce_Fraud_Detection",
    subtitle: "Fraud · Imbalance",
    cat: "ml",
    desc_es: "Detección de fraude en transacciones de comercio electrónico con datos fuertemente desbalanceados. Trabajo con técnicas de resampling, métricas adecuadas al problema (ROC-AUC, PR-AUC) y comparativa de modelos clásicos frente a ensembles.",
    desc_en: "Fraud detection on e-commerce transactions with strongly imbalanced data. Work with resampling techniques, metrics suited for the problem (ROC-AUC, PR-AUC) and a comparison between classical models and ensembles.",
    stack: ["scikit-learn", "pandas", "Imbalanced-learn"],
    href: "https://github.com/Zakariajava/E-Commerce_Fraud_Detection",
    accent: "pink",
  },
  {
    id: "nyc-taxi",
    name: "NYC-Taxi-Trip-Duration",
    subtitle: "Regression · Feature Eng.",
    cat: "ml",
    desc_es: "Predicción de la duración de viajes de taxi en Nueva York (competición clásica de Kaggle) con ingeniería de características geoespaciales, codificación de variables temporales y modelos de regresión. Buen caso de estudio para feature engineering.",
    desc_en: "Predicting the duration of NYC taxi trips (a classic Kaggle competition) with geospatial feature engineering, temporal variable encoding and regression models. A solid case study in feature engineering.",
    stack: ["XGBoost", "pandas", "Geopandas"],
    href: "https://github.com/Zakariajava/New_York_City_Taxi_Trip_Duration_pred",
    accent: "green",
  },
  {
    id: "heart-failure",
    name: "Heart-Failure-Prediction",
    subtitle: "Healthcare",
    cat: "ml",
    desc_es: "Predicción de eventos de insuficiencia cardíaca a partir de variables clínicas. Análisis exploratorio del dataset, selección de características y comparación entre modelos clásicos y árboles con boosting.",
    desc_en: "Prediction of heart failure events from clinical variables. Exploratory analysis of the dataset, feature selection and comparison between classical models and boosting trees.",
    stack: ["scikit-learn", "Healthcare"],
    href: "https://github.com/Zakariajava/HEART_FAILURE",
    accent: "pink",
  },
  {
    id: "heart-disease",
    name: "heart-disease-prediction",
    subtitle: "Healthcare · Interpretability",
    cat: "ml",
    desc_es: "Modelo de clasificación para predecir la presencia de enfermedad cardíaca con el dataset UCI. El foco está en la interpretabilidad: importancia de variables, análisis de errores y selección del umbral óptimo en función del coste de los falsos negativos.",
    desc_en: "A classification model to predict the presence of heart disease on the UCI dataset. The focus is on interpretability: feature importance, error analysis and optimal threshold selection based on the cost of false negatives.",
    stack: ["scikit-learn", "Logistic Regression"],
    href: "https://github.com/Zakariajava/heart-disease-prediction",
    accent: "violet",
  },
  {
    id: "housing-price",
    name: "Housing-Price",
    subtitle: "Regression",
    cat: "ml",
    desc_es: "Regresión sobre precios de viviendas con el dataset clásico de California: análisis exploratorio, tratamiento de outliers, codificación de variables categóricas y comparación entre regresión lineal, árboles y gradient boosting.",
    desc_en: "Regression on housing prices with the classic California dataset: exploratory analysis, outlier treatment, categorical variable encoding and a comparison between linear regression, trees and gradient boosting.",
    stack: ["scikit-learn", "pandas"],
    href: "https://github.com/Zakariajava/Housing-Price",
    accent: "cyan",
  },
  {
    id: "recsys",
    name: "Recommender-Systems",
    subtitle: "Collaborative Filtering",
    cat: "ml",
    desc_es: "Exploración práctica de sistemas de recomendación: filtrado colaborativo por usuario y por ítem, factorización matricial y recomendadores basados en contenido. Análisis de sus fortalezas y limitaciones según el tipo de datos.",
    desc_en: "A practical exploration of recommender systems: user-based and item-based collaborative filtering, matrix factorization and content-based recommenders. An analysis of their strengths and limitations depending on the type of data available.",
    stack: ["Surprise", "NumPy", "Collaborative Filtering"],
    href: "https://github.com/Zakariajava/Recommender_Systems",
    accent: "lilac",
  },
  {
    id: "collab-sockets",
    name: "collab-sockets",
    subtitle: "Networking · Java",
    cat: "sys",
    desc_es: "Aplicación Java para edición colaborativa en tiempo real a través de sockets TCP. Explora los problemas clásicos de sincronización, concurrencia y propagación de cambios entre varios clientes conectados al mismo servidor.",
    desc_en: "A Java application for real-time collaborative editing over TCP sockets. Explores the classic problems of synchronization, concurrency and change propagation across multiple clients connected to the same server.",
    stack: ["Java", "Sockets", "Concurrency"],
    href: "https://github.com/Zakariajava/collab-sockets",
    accent: "blue",
  },
  {
    id: "minilang",
    name: "minilang",
    subtitle: "Compilers",
    cat: "sys",
    desc_es: "Intérprete de un lenguaje de programación propio y minimalista. Cubre el flujo completo: análisis léxico, análisis sintáctico con construcción del AST, evaluación recursiva y manejo de errores.",
    desc_en: "An interpreter for a small, minimalist programming language of my own. Covers the full flow: lexical analysis, parsing with AST construction, recursive evaluation and error handling.",
    stack: ["Python", "Lexer", "Parser", "AST"],
    href: "https://github.com/Zakariajava/minilang",
    accent: "violet",
  },
  {
    id: "tienda-web",
    name: "TiendaWeb",
    subtitle: "Full-stack",
    cat: "sys",
    desc_es: "Pequeña aplicación web de tienda online implementada con JavaScript puro: catálogo de productos, carrito de la compra, flujo de compra básico. Proyecto útil para practicar manipulación del DOM, estado local y diseño de interfaces sin frameworks.",
    desc_en: "A small online shop web application implemented in pure JavaScript: product catalog, shopping cart, basic checkout flow. A useful project to practice DOM manipulation, local state and UI design without frameworks.",
    stack: ["JavaScript", "HTML/CSS"],
    href: "https://github.com/Zakariajava/TiendaWeb",
    accent: "pink",
  },
  {
    id: "phong",
    name: "PhongIllumination",
    subtitle: "Graphics · OpenGL",
    cat: "sys",
    desc_es: "Implementación del modelo de iluminación de Phong (ambiente, difusa y especular) en C con OpenGL. Un buen ejercicio para entender en detalle cómo se calcula el color de cada fragmento a partir de las propiedades del material y la luz incidente.",
    desc_en: "An implementation of the Phong illumination model (ambient, diffuse and specular) in C with OpenGL. A solid exercise to understand in detail how the color of each fragment is computed from material properties and incoming light.",
    stack: ["C", "OpenGL", "Shaders"],
    href: "https://github.com/Zakariajava/PhongIllumination",
    accent: "cyan",
  },
  {
    id: "isii-hospitales",
    name: "ISII-Administrar-Hospitales",
    subtitle: "Software Engineering",
    cat: "sys",
    desc_es: "Sistema de gestión hospitalaria desarrollado como práctica de Ingeniería del Software II. Patrones de diseño, separación de capas y trabajo en equipo con control de versiones. Ejercicio completo de software engineering clásico.",
    desc_en: "A hospital management system developed as a practical assignment for Software Engineering II. Design patterns, layered architecture and teamwork with version control. A complete classical software engineering exercise.",
    stack: ["Java", "OOP", "Design Patterns"],
    href: "https://github.com/Zakariajava/ISII_AdministrarHospitales",
    accent: "green",
  },
];

// ─── Skills (flat groups, no numbering) ───────────────────────────────────
const SKILLS = [
  { title_es: "Lenguajes",        title_en: "Languages",       items: ["Python", "C/C++", "Java", "JavaScript", "HTML5", "CSS3", "SQL"] },
  { title_es: "IA / ML",          title_en: "AI / ML",         items: ["PyTorch", "TensorFlow", "Keras", "scikit-learn", "XGBoost", "Transformers", "ViT", "CNNs"] },
  { title_es: "LLMs / Agents",    title_en: "LLMs / Agents",   items: ["LangChain", "LangGraph", "Ollama", "vLLM", "Qwen3", "ReAct"] },
  { title_es: "RAG / Retrieval",  title_en: "RAG / Retrieval", items: ["ChromaDB", "FAISS", "BM25", "Dense Embeddings", "RRF", "HyDE", "MultiQuery", "Cross-Encoder Reranking", "Knowledge Graphs"] },
  { title_es: "Backend",          title_en: "Backend",         items: ["FastAPI", "Flask", "Java EE (JSP/Servlets)", "REST APIs", "python-docx", "Microsoft Graph", "SharePoint", "TCP Sockets"] },
  { title_es: "Datos",            title_en: "Data",            items: ["pandas", "NumPy", "Geopandas", "Imbalanced-learn", "Surprise", "PostgreSQL", "MySQL", "SQLite", "MongoDB"] },
  { title_es: "DevOps / Sistemas",title_en: "DevOps / Systems",items: ["Docker", "Docker Compose", "Git", "GitHub Actions", "Linux", "OpenGL", "Selenium", "Playwright"] },
];

// ─── Certifications (39, individually verifiable on Coursera) ─────────────
// Grouped for display only. Order within groups: most relevant first.
const CERTS = [
  {
    id: "agents",
    title_es: "AI Agents & Agentic AI",
    title_en: "AI Agents & Agentic AI",
    items: [
      { name: "Building AI Agents and Agentic Workflows",                     issuer: "IBM",            date: "Oct 2025", url: "https://www.coursera.org/account/accomplishments/specialization/UROX1SUIDGWA" },
      { name: "Agentic AI with LangGraph, CrewAI, AutoGen and BeeAI",         issuer: "IBM",            date: "Sep 2025", url: "https://www.coursera.org/account/accomplishments/records/AWXAVIH36K1F" },
      { name: "IBM RAG and Agentic AI",                                       issuer: "IBM",            date: "Sep 2025", url: "https://www.coursera.org/account/accomplishments/specialization/X3774PPHATF6" },
      { name: "Agentic AI with LangChain and LangGraph",                      issuer: "IBM",            date: "Jul 2025", url: "https://www.coursera.org/account/accomplishments/verify/V82LDS06UQN4" },
      { name: "Fundamentals of Building AI Agents",                           issuer: "IBM",            date: "Jul 2025", url: "https://www.coursera.org/account/accomplishments/verify/ZGQWDFK0VO5H" },
      { name: "Build Multimodal Generative AI Applications",                  issuer: "IBM",            date: "Jul 2025", url: "https://www.coursera.org/account/accomplishments/verify/IW6XFBO3EGSN" },
    ],
  },
  {
    id: "rag",
    title_es: "RAG y bases vectoriales",
    title_en: "RAG & Vector Databases",
    items: [
      { name: "Advanced RAG with Vector Databases and Retrievers",            issuer: "IBM",            date: "Sep 2025", url: "https://www.coursera.org/account/accomplishments/verify/TSXE4ZG7MDFQ" },
      { name: "RAG for Generative AI Applications",                           issuer: "IBM",            date: "Sep 2025", url: "https://www.coursera.org/account/accomplishments/specialization/W2UQZCZMJHKV" },
      { name: "Vector Databases for RAG: An Introduction",                    issuer: "IBM",            date: "Jul 2025", url: "https://www.coursera.org/account/accomplishments/verify/K46CQ74O5CKA" },
      { name: "Build RAG Applications: Get Started",                          issuer: "IBM",            date: "Jul 2025", url: "https://www.coursera.org/account/accomplishments/verify/596YXNIVML4A" },
      { name: "Develop Generative AI Applications: Get Started",              issuer: "IBM",            date: "Jul 2025", url: "https://www.coursera.org/account/accomplishments/verify/2EPBGK0YLTIP" },
      { name: "AI Enhancement with Knowledge Graphs — Mastering RAG Systems", issuer: "Packt",          date: "Jul 2025", url: "https://www.coursera.org/account/accomplishments/verify/28DS7P6LJIE8" },
    ],
  },
  {
    id: "pytorch",
    title_es: "PyTorch",
    title_en: "PyTorch",
    items: [
      { name: "PyTorch for Deep Learning",                                    issuer: "DeepLearning.AI",date: "Nov 2025", url: "https://www.coursera.org/account/accomplishments/specialization/ZYEUD91L9FYS" },
      { name: "PyTorch: Advanced Architectures and Deployment",               issuer: "DeepLearning.AI",date: "Nov 2025", url: "https://www.coursera.org/account/accomplishments/records/CK4L1IG1BJ5L" },
      { name: "PyTorch: Techniques and Ecosystem Tools",                      issuer: "DeepLearning.AI",date: "Nov 2025", url: "https://www.coursera.org/account/accomplishments/records/CR0RUHDBQ5CS" },
      { name: "PyTorch: Fundamentals",                                        issuer: "DeepLearning.AI",date: "Nov 2025", url: "https://www.coursera.org/account/accomplishments/records/6PJ2XY48LZZO" },
      { name: "Foundations and Core Concepts of PyTorch",                     issuer: "Packt",          date: "Sep 2025", url: "https://www.coursera.org/account/accomplishments/verify/OJG0HNZ0ZQC9" },
      { name: "Building and Training Neural Networks with PyTorch",           issuer: "Packt",          date: "Sep 2025", url: "https://www.coursera.org/account/accomplishments/verify/N4BCRQSYJ7D2" },
    ],
  },
  {
    id: "dl",
    title_es: "Deep Learning",
    title_en: "Deep Learning",
    items: [
      { name: "Deep Learning Specialization",                                 issuer: "DeepLearning.AI",date: "Feb 2025", url: "https://www.coursera.org/account/accomplishments/specialization/EOAJ4XETDWMR" },
      { name: "Neural Networks and Deep Learning",                            issuer: "DeepLearning.AI",date: "2024",     url: "https://www.coursera.org/account/accomplishments/certificate/KNJNB8WQWAJP" },
      { name: "Improving Deep Neural Networks: Hyperparameter Tuning & Regularization", issuer: "DeepLearning.AI", date: "2024", url: "https://www.coursera.org/account/accomplishments/certificate/CNCPQJS4KTFE" },
      { name: "Structuring Machine Learning Projects",                        issuer: "DeepLearning.AI",date: "2024",     url: "https://www.coursera.org/account/accomplishments/verify/Z3KQ6DQXD2GM" },
      { name: "Convolutional Neural Networks",                                issuer: "DeepLearning.AI",date: "2024",     url: "https://www.coursera.org/account/accomplishments/certificate/Y4QTHRNL3HE7" },
      { name: "AI for Medicine Specialization",                               issuer: "DeepLearning.AI",date: "Oct 2025", url: "https://www.coursera.org/account/accomplishments/specialization/6MOISRA2N5WK" },
    ],
  },
  {
    id: "ml",
    title_es: "Fundamentos de Machine Learning",
    title_en: "Machine Learning Foundations",
    items: [
      { name: "Machine Learning",                                             issuer: "DeepLearning.AI",date: "2024",     url: "https://www.coursera.org/account/accomplishments/certificate/9PL5C8QDGYQ6" },
      { name: "IBM Introduction to Machine Learning",                         issuer: "IBM",            date: "Nov 2024", url: "https://www.coursera.org/account/accomplishments/specialization/59X2YJWXX9SS" },
      { name: "Supervised Machine Learning: Classification",                  issuer: "IBM",            date: "Nov 2024", url: "https://www.coursera.org/account/accomplishments/certificate/HYIO24EKA6SX" },
      { name: "Supervised Machine Learning: Regression",                      issuer: "IBM",            date: "2024",     url: "https://www.coursera.org/account/accomplishments/verify/LDQ28KIIHHG7" },
      { name: "Unsupervised Machine Learning",                                issuer: "IBM",            date: "2024",     url: "https://www.coursera.org/account/accomplishments/certificate/52M2R676600S" },
      { name: "Exploratory Data Analysis for Machine Learning",               issuer: "IBM",            date: "2024",     url: "https://www.coursera.org/account/accomplishments/certificate/8PVON5MQJ62R" },
    ],
  },
  {
    id: "transformers",
    title_es: "Transformers y NLP",
    title_en: "Transformers & NLP",
    items: [
      { name: "Transformer Models and BERT Model",                            issuer: "Google Cloud",   date: "Mar 2025", url: "https://www.coursera.org/account/accomplishments/verify/K2LDLD7XJIM6" },
      { name: "Attention Mechanism",                                          issuer: "Google Cloud",   date: "Feb 2025", url: "https://www.coursera.org/account/accomplishments/verify/LJPL5IN4LHON" },
    ],
  },
  {
    id: "cloud-web",
    title_es: "Cloud, redes y web",
    title_en: "Cloud, Networks & Web",
    items: [
      { name: "AI Infrastructure and Operations Fundamentals",                issuer: "NVIDIA",         date: "Feb 2025", url: "https://www.coursera.org/account/accomplishments/verify/NFNQ1HP3ODGH" },
      { name: "Introduction to Networking",                                   issuer: "NVIDIA",         date: "Feb 2025", url: "https://www.coursera.org/account/accomplishments/verify/AUQMCFVGVRP0" },
      { name: "Google AI Essentials",                                         issuer: "Google",         date: "Feb 2025", url: "https://www.coursera.org/account/accomplishments/verify/X51IOTBS2BSE" },
      { name: "Advanced Styling with Responsive Design",                      issuer: "U. of Michigan", date: "Feb 2025", url: "https://www.coursera.org/account/accomplishments/verify/VHSLGPRZGP26" },
      { name: "Interactivity with JavaScript",                                issuer: "U. of Michigan", date: "Feb 2025", url: "https://www.coursera.org/account/accomplishments/verify/JODZD9YLKDBT" },
      { name: "Introduction to CSS3",                                         issuer: "U. of Michigan", date: "Feb 2025", url: "https://www.coursera.org/account/accomplishments/verify/FDU5K7VCNMBP" },
      { name: "Introduction to HTML5",                                        issuer: "U. of Michigan", date: "Feb 2025", url: "https://www.coursera.org/account/accomplishments/verify/B9898ISXJUTR" },
    ],
  },
];

// ─── Languages ────────────────────────────────────────────────────────────
const LANGS = [
  { name_es: "Bereber",  name_en: "Berber",  level_es: "Nativo",            level_en: "Native",            pct: 100 },
  { name_es: "Árabe",    name_en: "Arabic",  level_es: "Nativo",            level_en: "Native",            pct: 100 },
  { name_es: "Español",  name_en: "Spanish", level_es: "C1-C2 · Profesional", level_en: "C1-C2 · Professional", pct: 95  },
  { name_es: "Inglés",   name_en: "English", level_es: "B2-C1 · Profesional", level_en: "B2-C1 · Professional", pct: 86  },
  { name_es: "Francés",  name_en: "French",  level_es: "B2 · Profesional",    level_en: "B2 · Professional",    pct: 70  },
];

// ─── Contact ──────────────────────────────────────────────────────────────
const CONTACT = {
  email:    "zakariaabouhammadi@gmail.com",
  github:   "https://github.com/Zakariajava",
  linkedin: "https://www.linkedin.com/in/zakaria-abouhammadi-52aa5b1a0/",
  web:      "https://zakariajava.github.io",
  cvEs:     "assets/cv/CV_Español.pdf",
  cvEn:     "assets/cv/CV_ingles.pdf",
  photo:    "assets/photo/imagen.jpeg",
};

// ─── Keep the About stats in sync with the actual data ───────────────────
// stats[0] = projects, stats[1] = certifications, stats[3] = languages.
// stats[2] (internship hours) stays hardcoded — not derivable.
const _totalCerts = CERTS.reduce((sum, g) => sum + g.items.length, 0);
[i18n.es, i18n.en].forEach(L => {
  L.s_about.stats[0].n = String(PROJECTS.length);
  L.s_about.stats[1].n = String(_totalCerts);
  L.s_about.stats[3].n = String(LANGS.length);
});

window.PORTFOLIO_DATA = { i18n, PROJECTS, SKILLS, CERTS, LANGS, CONTACT };
